export const FETCH_USER = "FETCH_USER";
export const RECEIVE_USER = "RECEIVE_USER";
export const FETCH_FAILED = "FETCH_FAILED";
export const OPEN_SELECT_JFG = "OPEN_SELECT_JFG";
export const OPEN_SELECT_JF = "OPEN_SELECT_JF";
export const RECEIVE_JOB_FAMILY_GROUP = "RECEIVE_JOB_FAMILY_GROUP";
export const RECEIVE_JOB_FAMILY_GROUP_DESCRIPTION =
  "RECEIVE_JOB_FAMILY_GROUP_DESCRIPTION";
export const CHANGE_SELECTED_JFG = "CHANGE_SELECTED_JFG";
export const RECEIVE_JOB_FAMILY = "RECEIVE_JOB_FAMILY";
export const RECEIVE_JOB_FAMILY_DESCRIPTION = "RECEIVE_JOB_FAMILY_DESCRIPTION";
export const CHANGE_SELECTED_JF = "CHANGE_SELECTED_JF";
